"""The platform-facing half of the dictionary and the catalogue.

**Not a pure zone**, and that is the point: this package is where Odoo is allowed
to exist, so that `dictionary/` and `catalogue/` never have to. Everything here
produces the inputs those two take as arguments — entries, attribute descriptors,
readable references — and produces nothing else.

`04` §6.5 says the product's contact with the platform is concentrated in two
components, the Executor and the Catalogue, and that keeping them thin is the
main defence against the recurring cost of maintenance on a ten-year horizon.
This is the Catalogue's half of that surface.

| Module | Contenuto |
|---|---|
| `l0.py` | the derived level, generated by metadata introspection (D84, `06` §2.4) |
| `permissions.py` | readable references and the permission fingerprint (D39, D40) |
| `filters.py` | saved filters as category proposals (D35), into the L3 queue |
"""
