"""L0 — the derived level, generated by introspection (D84, `06` §2.4).

L0 is **not a copy of the schema**. A selection already applies here, because this
is where the quality of the catalogue is born (`06` §5.2): `sale.order` exposes more
than 85 fields and the ones a person might name are of the order of twenty.

Two properties are normative and shape every function below.

**Regenerable identically.** L0 is rebuilt at every module update, so the exclusion
criteria are deterministic and declared, never a judgement made case by case. A
correction to L0 would be lost at the next regeneration — corrections go in L2,
which has precedence (`06` §2.2).

**Never edited by hand.** Nothing here writes; it reads the registry and returns
data. Persisting it is somebody else's decision, and making that explicit is what
keeps the regeneration honest.

## The reference of an entity

`sale.order` becomes `sale_order`. Deliberately mechanical: the reference is an
**identifier**, it enters saved states, and D36 suspends orphaned entries rather
than deleting them — so it must not change because someone improved a label. The
readable name of the entity is a **term** (T1), which is exactly the thing that may
change freely, and the language the interpretation is shown in.
"""

from __future__ import annotations

# Gli elenchi vivono nella zona pura `platform_types` (D109, D117): sono fatti
# della piattaforma, uguali in ogni installazione, e li devono poter leggere
# anche i test puri che girano senza Odoo.
from ..platform_types import MIXIN_PREFIXES, SYSTEM_FIELDS  # noqa: F401

MIXIN_FIELDS = frozenset({
    "my_activity_date_deadline", "has_message", "is_follower",
})

#: Field types that cannot be usefully filtered or ordered. Rule 4 of §5.3.
UNQUERYABLE_TYPES = frozenset({"binary", "html", "image", "json"})

#: Models that are never entities: transient wizards, abstract mixins and the
#: relation tables Odoo creates for many2many. None of them is something a person
#: names in a sentence.
EXCLUDED_MODEL_PREFIXES = ("ir.", "base.", "bus.", "report.", "web_")


def reference_of_model(model_name: str) -> str:
    """`sale.order` -> `sale_order`. An identifier, not a label."""
    return model_name.replace(".", "_")


def reference_of_field(model_name: str, field_name: str) -> str:
    return f"{reference_of_model(model_name)}.{field_name}"


def is_candidate_entity(model) -> bool:
    """Whether a model can be an entity of an interrogation (`06` §2.4).

    Transient and abstract models are excluded structurally rather than by
    label-guessing: a wizard is not something a user asks to see a list of.
    """
    if model._transient or model._abstract:
        return False
    if model._name.startswith(EXCLUDED_MODEL_PREFIXES):
        return False
    return True


def _is_mixin_field(name: str) -> bool:
    return name.startswith(MIXIN_PREFIXES) or name in MIXIN_FIELDS


def default_view_fields(env, model_name: str) -> frozenset[str]:
    """Field names appearing in the model's default list and form views.

    Rule 8 of §5.3, which `06` calls the most productive of the nine: the fields
    Odoo shows by default are the ones the module's designers judged relevant for the
    user. A judgement of pertinence already made, free, and aligned by construction
    with what people see every day.

    Read through `get_views`, so inherited views and customisations are included —
    a customer who added a column to the list view has said something about
    relevance, and this is where the system hears it.
    """
    found: set[str] = set()
    for view_type in ("list", "form"):
        try:
            description = env[model_name].get_view(view_type=view_type)
        except Exception:
            # A model without that view type is ordinary, not an error. Failing here
            # would make the whole of L0 depend on every model having a form view.
            continue
        # Odoo 18's `get_view` reports the fields each model contributes to the view.
        for name in (description.get("models") or {}).get(model_name, ()):
            found.add(name)
    return frozenset(found)


def attribute_descriptors(env, model_name: str, *, l1_relevant=frozenset(),
                          l2_exposed=None, historical_uses=None):
    """Descriptors for `catalogue.exposure`, one per field of the model.

    Returns the plain descriptors, **all of them**: deciding what is exposed is
    §5.3's job and it lives in the pure zone. Splitting it this way is what makes the
    nine rules testable without a database, and it is why this function looks
    uninteresting — it is supposed to.

    `fields_get` is the right primitive for a second reason beyond convenience: it
    already drops the fields whose `groups` the user does not hold, so field-level
    access is applied here, before selection, as §5.9 requires.
    """
    from ..catalogue.exposure import Attribute  # local: keeps the pure zone importable

    l2_exposed = l2_exposed or {}
    historical_uses = historical_uses or {}
    in_views = default_view_fields(env, model_name)

    descriptors = []
    for name, info in env[model_name].fields_get().items():
        descriptors.append(Attribute(
            name=name,
            label=info.get("string") or "",
            type=info.get("type") or "char",
            stored=bool(info.get("store", True)),
            searchable=bool(info.get("searchable", info.get("store", True))),
            in_default_views=name in in_views,
            is_system=name in SYSTEM_FIELDS,
            is_technical_mixin=_is_mixin_field(name),
            l1_relevant=name in l1_relevant,
            l2_exposed=l2_exposed.get(name),
            historical_uses=historical_uses.get(name, 0),
        ))
    return descriptors


#: Separatori dentro un'etichetta di modello: `Lead/Opportunità`, `Ordine, preventivo`.
#: Ogni pezzo e' un nome per conto suo, non una parte di un nome solo.
_LABEL_SEPARATORS = ("/", ",", "&")

#: Sotto questa lunghezza un nome di menu non e' un nome di entita': e' un'abbreviazione
#: o un verbo, e indicizzarlo produce collisioni invece di riconoscimenti.
_MIN_TERM = 4


def _entity_terms(env, model_name: str, label: str) -> list[str]:
    """I nomi con cui una persona chiama questa entita' (D126).

    **Il difetto che chiude.** L'entita' aveva **un termine solo: l'etichetta grezza**.
    `crm.lead` si chiamava `Lead/Opportunità`, e nessuna frase italiana contiene quella
    stringa: il normalizzatore la riduce ai gettoni `lead opportunita`, che come termine
    unico pretende di trovarli tutti e due di fila. Misurato sul database vero, la fase
    A non riconosceva **nessuna** entita' — nemmeno *«opportunita'»*, che e' meta' del
    nome del modello.

    **Perche' raccogliere e non generare.** Le parole che l'utente usa sono gia' scritte
    nell'installazione, e sono vere:

    * l'etichetta, **e i suoi pezzi**: `Lead/Opportunità` sono due nomi, non uno;
    * i nomi delle **azioni** che aprono quel modello da un menu;
    * i nomi delle **voci di menu** che ci portano — le parole che l'utente preme da
      anni, gia' tradotte e gia' rinominate se il cliente le ha rinominate.

    Il plurale non si costruisce con regole di morfologia italiana, che sbaglierebbero
    su *«Registrazioni contabili»* e sulle parole straniere: **si legge nel menu**, dove
    e' gia' scritto. Il modello si chiama *Ordine di vendita*, il menu si chiama
    *Ordini di vendita*, e il secondo e' quello che la gente dice.

    Chiedere i sinonimi al modello sarebbe P4: un nome di entita' inventato e' il
    fallimento che D14 e D105 esistono per impedire.

    **Solo le azioni che un menu raggiunge.** `act_window` ne esiste una pila per ogni
    modello, molte con nomi di servizio; quelle appese a un menu sono quelle che una
    persona ha davanti.
    """
    terms: list[str] = []

    def _consider(text):
        for candidate in _split_label(text or ""):
            if candidate and candidate not in terms:
                terms.append(candidate)

    _consider(label)
    for name in _menu_facing_names(env, model_name):
        if len(name) >= _MIN_TERM:
            _consider(name)
    return terms or [label]


def _split_label(text: str) -> list[str]:
    """L'etichetta intera **piu'** i suoi pezzi.

    Intera perche' chi dice *«lead/opportunità»* deve trovarla; a pezzi perche' chi dice
    *«i lead»* pure. Sono termini distinti e non si escludono: il vocabolario si somma
    (`06` §2.2), anche dentro un livello.
    """
    text = (text or "").strip()
    if not text:
        return []
    parts = [text]
    for separator in _LABEL_SEPARATORS:
        if separator in text:
            parts.extend(piece.strip() for piece in text.split(separator))
            break
    return [part for part in parts if part]


def _menu_facing_names(env, model_name: str) -> list[str]:
    """I nomi con cui questo modello compare nei menu.

    Nessun `sudo` (**V2**): si legge con i diritti di chi sta chiedendo, ed e' giusto
    cosi' — un utente che non vede il menu degli ordini non deve nemmeno saperne il
    nome. Se la lettura non riesce si torna vuoti: un nome in meno rende la fase A meno
    brava, un'eccezione qui renderebbe il dizionario non costruibile.
    """
    try:
        actions = env["ir.actions.act_window"].search(
            [("res_model", "=", model_name)])
        if not actions:
            return []
        menus = env["ir.ui.menu"].search(
            [("action", "in", [f"ir.actions.act_window,{a.id}" for a in actions])])
        names = list(menus.mapped("name"))
        # Il nome dell'azione conta solo se un menu la raggiunge: e' il filtro che
        # tiene fuori le azioni di servizio.
        names.extend(action.name for action in actions
                     if action.id in {m.action.id for m in menus if m.action})
        return [name for name in names if name]
    except Exception:  # noqa: BLE001 — vedi il docstring
        return []


def naming_entries(env, model_name: str) -> list[dict]:
    """T1 entries for the entity and its fields, from the translated labels.

    The labels are already translated in the user's language: `06` §3.2 says L0 is
    the most numerous and most harmless type, and it is free — Odoo ships it.
    """
    entries: list[dict] = []
    model = env[model_name]
    label = env["ir.model"]._get(model_name).name or model_name
    entries.append({
        "type": "T1", "level": "L0",
        "ref": reference_of_model(model_name),
        "terms": _entity_terms(env, model_name, label),
    })
    for name, info in model.fields_get().items():
        string = info.get("string")
        if not string or string == name:
            # Rule 6 of §5.3: a field with no usable label is not nameable in
            # natural language, so there is no term to record.
            continue
        if name in SYSTEM_FIELDS or _is_mixin_field(name):
            continue
        if info.get("type") in UNQUERYABLE_TYPES:
            continue
        entries.append({
            "type": "T1", "level": "L0",
            "ref": reference_of_field(model_name, name),
            "terms": [string],
        })
    return entries


def enum_entries(env, model_name: str) -> list[dict]:
    """T2 entries: the admitted values of selection fields, with their labels.

    This is what lets the catalogue give the model the valid values **without
    showing it a single record** (`06` §3.3): they are schema metadata, not content,
    and A6 is untouched.
    """
    entries: list[dict] = []
    for name, info in env[model_name].fields_get().items():
        if info.get("type") != "selection":
            continue
        for value, label in info.get("selection") or ():
            if not label:
                continue
            entries.append({
                "type": "T2", "level": "L0",
                "ref": reference_of_field(model_name, name),
                "value": value,
                "terms": [label],
            })
    return entries


def generate(env, model_names) -> list[dict]:
    """The whole of L0 for a set of models.

    Deterministic: the same registry produces the same list, in the same order. That
    is D84's requirement and also what makes a diff between two regenerations
    readable — which is how a module update's effect on the dictionary gets noticed
    at all.
    """
    entries: list[dict] = []
    for model_name in sorted(model_names):
        entries.extend(naming_entries(env, model_name))
        entries.extend(enum_entries(env, model_name))
    return entries


def candidate_entities(env) -> list[str]:
    """Models that can be entities, in a stable order."""
    names = []
    for model_name, model in env.registry.items():
        if is_candidate_entity(env[model_name]):
            names.append(model_name)
    return sorted(names)
