"""The utterance crosses a process boundary, and must not do it in clear (D96).

Part 6 is the first place in the product where the user's sentence has to **outlive
the request that carried it**: acceptance runs on an HTTP worker, interpretation runs
on a cron process, and the only channel between the two is the database. Until now
the utterance never touched storage — part 4 went as far as stripping `provenance`
from the state for exactly this reason.

The binding rule is one line of the registry §9: *"utterances are never persisted in
clear"* (D54). D54's own mechanism — pseudonymisation at ingress with a separate,
encrypted mapping — does not exist yet, and D96 does not pretend otherwise. What it
establishes is narrower and available now:

* the utterance is **transient**, not retained: it exists in the queue row between
  acceptance and interpretation, bounded by L4 (thirty seconds), and is erased the
  moment the turn reaches a final state — success, failure or expiry;
* while it is there, it is **encrypted with a key held in the environment**, so a
  database dump never contains an utterance. That is D76's argument applied to a
  different secret: *"a copy of the database must not produce credentials"*, and a
  copy of the database must not produce sentences either;
* the key is named by an environment variable and **never stored**, and if it is
  absent acceptance **refuses** rather than falling back to clear text. Fail closed,
  like `NLI_ALLOWED_HOSTS` under D77: a protection that degrades silently to nothing
  is worse than one that was never claimed.

What this is **not**: it is not pseudonymisation, and it does not give per-subject
erasure. It does not need to — nothing is retained. When D54 lands, the mapping
replaces this and the retention question moves with it, in the same change.
"""

from __future__ import annotations

import os

from cryptography.fernet import Fernet, InvalidToken

#: The variable that names the key. The value is the key itself, as generated by
#: `Fernet.generate_key()`; there is no default and no derivation from a passphrase,
#: because a key derived from something memorable is a key that will be memorable.
KEY_VARIABLE = "NLI_UTTERANCE_KEY"


class VaultUnavailable(Exception):
    """No usable key. Acceptance refuses; it never stores the sentence in clear."""


def _key() -> bytes:
    raw = os.environ.get(KEY_VARIABLE, "").strip()
    if not raw:
        raise VaultUnavailable(
            f"{KEY_VARIABLE} is not set: an utterance would have to be written in "
            "clear to cross to the cron process, which D54 forbids. Generate one "
            "with: python3 -c 'from cryptography.fernet import Fernet; "
            "print(Fernet.generate_key().decode())'"
        )
    return raw.encode("ascii")


def available() -> bool:
    """Whether the queue can accept anything at all, checked at acceptance."""
    try:
        Fernet(_key())
    except (VaultUnavailable, ValueError, TypeError):
        return False
    return True


def seal(utterance: str) -> str:
    """Encrypt an utterance for its short stay in the queue."""
    try:
        cipher = Fernet(_key())
    except (ValueError, TypeError) as error:
        raise VaultUnavailable(f"{KEY_VARIABLE} is not a valid key: {error}") from error
    return cipher.encrypt(utterance.encode("utf-8")).decode("ascii")


def unseal(sealed: str) -> str:
    """Decrypt an utterance for the one component that needs it: the Interpreter.

    A token that does not open is not an error to swallow. It means the key changed
    while turns were queued, and the turns concerned can never be executed: they must
    fail visibly rather than be interpreted as an empty sentence, which would produce
    a plausible answer to a question nobody asked.
    """
    try:
        cipher = Fernet(_key())
        return cipher.decrypt(sealed.encode("ascii")).decode("utf-8")
    except (InvalidToken, ValueError, TypeError) as error:
        raise VaultUnavailable(
            "the stored utterance cannot be opened with the current key"
        ) from error
